# Generated by Django 2.2.17 on 2021-07-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
