# Generated by Django 2.2.17 on 2021-07-15 10:17

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Demo', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', pgcrypto.fields.EmailPGPPublicKeyField(max_length=254)),
                ('salary', pgcrypto.fields.IntegerPGPPublicKeyField()),
            ],
        ),
    ]
