# Generated by Django 2.2.17 on 2021-07-15 11:38

from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0004_auto_20210715_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', pgcrypto.fields.CharPGPSymmetricKeyField(max_length=150)),
                ('address', pgcrypto.fields.TextPGPPublicKeyField()),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Demo.Person')),
            ],
        ),
    ]
