# Generated by Django 2.2.17 on 2021-07-15 11:45

from django.db import migrations
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0005_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='address',
            field=pgcrypto.fields.TextPGPSymmetricKeyField(),
        ),
    ]
