# Generated by Django 2.2.17 on 2021-07-15 11:56

from django.db import migrations, models
import pgcrypto.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0006_auto_20210715_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', pgcrypto.fields.CharPGPSymmetricKeyField(max_length=150)),
                ('person', models.ManyToManyField(to='Demo.Person')),
            ],
        ),
    ]
